/** The UI's language. Lives in the DB (`settings.idioma`, the same knob that
 *  governs what the agent writes) and is cached in `localStorage` only so the
 *  first frame can paint without waiting on the network. The DB is the source
 *  of truth: if the cache lies, `initLang` corrects it — the reload, if any,
 *  is `Language.tsx`'s job, not this function's. */
export type Lang = "es" | "en"

const KEY = "orq.idioma"
let current: Lang = "es"

export function lang(): Lang {
  return current
}

/** Updates the language both in memory and in localStorage. Silently ignores
 *  invalid values (not "es" or "en"). */
export function setLang(code: unknown): void {
  if (code !== "es" && code !== "en") return
  current = code
  try {
    localStorage.setItem(KEY, code)
  } catch {
    // Storage write failed; the value is in memory, which is enough
  }
}

/** Resolves the language before the first render. Starts from the cache — if
 *  there is none, Spanish, the backend's default — and queries the DB afterwards.
 *  Without the cache, the app paints a Spanish frame and jumps to English in
 *  front of the user. Swallows all errors to guarantee it never rejects: this
 *  runs before React mounts, so a rejection is a blank page with no way to
 *  recover. */
export async function initLang(): Promise<void> {
  try {
    const cached = localStorage.getItem(KEY)
    if (cached === "es" || cached === "en") current = cached
  } catch {
    // Storage unavailable or disabled (e.g., Safari private browsing, sandboxed iframe);
    // stay with default "es"
  }

  try {
    const r = await fetch("/api/idioma")
    if (!r.ok) return                       // the DB is authoritative, but if it
    const { idioma } = await r.json()       // doesn't answer the cache beats nothing
    if (idioma === "es" || idioma === "en") {
      current = idioma
      try {
        localStorage.setItem(KEY, idioma)
      } catch {
        // Storage write failed; the value is in memory, which is enough
      }
    }
  } catch {
    // no network, nothing to correct: stay with the cache
  }
}

const ES: Record<string, string> = {
  "common.save": "Guardar",
  "common.cancel": "Cancelar",
  "common.dismissError": "Descartar el error",
  "common.projects": "Proyectos",
  "common.newProject": "Nuevo proyecto",
  "common.settings": "Ajustes",
  "common.discard": "Descartar",
  "common.edit": "Editar",
  "common.delete": "Borrar",
  "common.view": "Ver",
  "common.loading": "cargando…",
  "common.languageTitle": "Idioma de los entregables",
  "common.archiveTitle": "Archivo de entregables",
  "app.noProjectNamed": "No hay ningún proyecto llamado",
  "app.backHome": "Volver al inicio",
  "app.loadingTicket": "Cargando el ticket…",
  "app.unsavedTitle": "Hay cambios sin guardar.",
  "app.unsavedBody": "Si sales ahora se pierden.",
  "home.runningPrefix": "corriendo",
  "home.noActiveRuns": "sin corridas activas · el runner corre una a la vez",
  "home.tagline": "elige un proyecto para encolar tickets · [*] ajustes para engines, modelos y archivo",
  "home.ticketsSuffix": "tickets",
  "home.openSuffix": "abiertos",
  "home.primaryLabel": "principal:",
  "home.noRepos": "sin repos",
  "home.mountedSuffix": "montados",
  "home.noProjectsYet": "Aún no hay proyectos. Agrega uno para poder encolar tickets.",
  "home.confirmDeleteTitle": "¿Borrar el proyecto",
  "home.confirmDeleteBody": "Los tickets ya creados no se rompen: cada uno guardó su propia copia de los datos. Pero no vas a poder encolar nuevos.",
  "topbar.pluginTag": "ticket-agent",
  "topbar.toLightTheme": "Cambiar a tema claro",
  "topbar.toDarkTheme": "Cambiar a tema oscuro",
  "info.explanationPrefix": "Explicación",
  "settings.phaseRunTitle": "Cómo corre cada fase",
  "settings.globalNextRun": "global · aplica a la siguiente corrida",
  "settings.globalOptional": "global · opcional",
  "archive.dirAriaLabel": "Directorio de archivo",
  "archive.dirPlaceholder": "D:/archivo-tickets",
  "archive.savePath": "Guardar ruta",
  "language.spanish": "Español",
  "language.english": "English",
  "repotable.noDescription": "sin descripción",
  "repotable.primary": "principal",
  "projectheader.reposSeen": "Repos que verá el agente",
  "projectheader.onlyOneRepo": "Solo un repo. Se añaden más al editar el proyecto.",
  "ticketlist.originAriaLabel": "Origen del ticket",
  "ticketlist.tabAdo": "Ticket de Azure",
  "ticketlist.tabRequest": "Solicitud directa",
  "ticketlist.workItemIdLabel": "ID del work item",
  "ticketlist.add": "+ Añadir",
  "ticketlist.workItemUrlHint": "El número del final de la URL en Azure DevOps:",
  "ticketlist.whatDoYouNeedLabel": "Qué necesitas",
  "ticketlist.requestPlaceholder": "Qué necesitas, dónde vive hoy (pantalla, módulo, repo), por qué, y cómo sabrás que quedó bien.",
  "ticketlist.firstLineTitle": "La primera línea será el título en la lista.",
  "ticketlist.launchPhase1Hint": "Lanza la Fase 1; el resto se lanza desde el detalle",
  "ticketlist.analyze": "Analizar",
  "ticketlist.reanalyze": "Re-analizar",
  "ticketlist.empty": "Sin tickets en este proyecto. Escribe un id arriba para añadir el primero.",
  "ticketdetail.runHistory": "Historial de corridas",
  "ticketdetail.queued": "en cola",
  "ticketdetail.noRuns": "Sin corridas aún.",
  "ticketdetail.restore": "Restaurar",
  "ticketdetail.lastRunLog": "Log de la última corrida",
  "ticketdetail.logPlaceholder": "(el log aparecerá cuando arranque la corrida)",
  "ticketdetail.confirmDeleteTitle": "¿Borrar el ticket",
  "ticketdetail.confirmDeleteBody": "Se borran sus corridas y sus logs. Los artefactos que el agente escribió en el repo se quedan donde están.",
  "ticketdetail.fileExistsTitle": "El archivo ya existe",
  "ticketdetail.fileExistsBody": "Reemplazarlo con la versión del snapshot. La versión actual se pierde (salvo que otra corrida la haya archivado).",
  "ticketdetail.replace": "Reemplazar",
  "decisions.oneForYou": "decisión para ti",
  "decisions.manyForYou": "decisiones para ti",
  "decisions.oneBlocks": "bloquea la fase siguiente",
  "decisions.manyBlock": "bloquean la fase siguiente",
  "decisions.allAnswered": "decisiones respondidas",
  "decisions.blocksNextPhase": "Bloquea la fase siguiente",
  "decisions.decideWithProposal": "Decide — con propuesta",
  "decisions.answeredSuffix": "respondido",
  "decisions.acceptProposal": "Aceptar propuesta",
  "decisions.yourAnswerPlaceholder": "Tu respuesta…",
  "decisions.answerForAriaLabel": "Respuesta para",
  "decisions.respond": "Responder",
  "status.queued": "registrado",
  "status.running": "corriendo",
  "status.analyzed": "analizado",
  "status.briefed": "briefeado",
  "status.surveyed": "sondeado",
  "status.planned": "planificado",
  "status.implemented": "implementado",
  "status.error": "error",
  "status.ok": "ok",
  "status.parcial": "parcial",
  "status.corriendo": "corriendo",
  "status.pendiente": "pendiente",
  "status.activeRunSelf": "esta corrida ya está en marcha",
  "status.activeRunOther": "esperando a #{ado_id} en {project}",
  "status.phaseNotAvailable": "esta fase todavía no existe",
  "status.deliverableMissing": "{list} declaró un entregable que no está en disco",
  "status.needsGreen": "necesita {list} en verde",
  "status.orSeparator": "o",
  "phase.analyze": "Análisis",
  "phase.brief": "Brief",
  "phase.survey": "Sondeo",
  "phase.consolidate": "Consolidación",
  "phase.design": "Plan",
  "phase.implement": "Código",
  "models.infoLabel": "Cómo funciona esto",
  "models.stageAnalyzeTitle": "1 · Entender el ticket",
  "models.stageAnalyzeNote": "Dos caminos al mismo documento, y eliges uno al lanzar: Análisis si el proyecto es un solo repo; Brief → Sondeo → Consolidación si son varios.",
  "models.stageDesignTitle": "2 · Planear el cambio",
  "models.stageImplementTitle": "3 · Escribir el código",
  "models.tableHeaderPhase": "fase",
  "models.tableHeaderEngine": "motor",
  "models.tableHeaderModel": "modelo",
  "models.tableHeaderEffort": "esfuerzo",
  "models.selectorDefault": "(por defecto)",
  "models.engineLabel": "Motor de",
  "models.modelLabel": "Modelo de",
  "models.effortLabel": "Esfuerzo de",
  "models.saveButton": "Guardar configuración de fases",
  "timeline.preparing": "Preparando…",
  "timeline.prepareRepo": "Preparar repo",
  "timeline.blocksLabel": "bloquea",
  "timeline.notAvailableYet": "no disponible aún",
  "timeline.noRunsShort": "sin corridas",
  "timeline.oneRun": "corrida",
  "timeline.manyRuns": "corridas",
  "timeline.rerun": "Re-correr",
  "timeline.run": "Correr",
  "timeline.runWithAdjustmentsTitle": "Correr con instrucciones de ajuste",
  "timeline.adjustAndRunAriaLabel": "Ajustar y correr",
  "timeline.adjust": "Ajustar",
  "timeline.taskLabel": "tarea",
  "timeline.taskOfLabel": "de",
  "timeline.branchLabel": "Rama",
  "timeline.artifactLabel": "Artefacto",
  "timeline.filesLabel": "archivos",
  "timeline.restoreFromArchive": "Restaurar desde el archivo",
  "timeline.adjustmentFor": "Ajuste para",
  "timeline.howAdjustmentApplies": "Cómo aplicar el ajuste",
  "timeline.newSession": "Sesión nueva",
  "timeline.noPreviousSessionTitle": "Esta fase no tiene una sesión previa que continuar",
  "timeline.continuePrevious": "Continuar la anterior",
  "timeline.continuationLabel": "continuación",
  "timeline.runWithAdjustmentButton": "Correr con este ajuste",
  "timeline.viewing": "Viendo",
  "timeline.truncatedNote": "truncado a 512 KB, se muestra solo el inicio",
  "timeline.viewRaw": "ver crudo",
  "timeline.viewRendered": "ver renderizado",
  "timeline.close": "cerrar",
  "projectform.errorName": "Ponle un nombre al proyecto.",
  "projectform.errorOrg": "Falta la organización de Azure DevOps.",
  "projectform.errorProject": "Falta el proyecto de Azure DevOps.",
  "projectform.errorReposMissing": "Necesitas al menos un repo con su ruta.",
  "projectform.errorPrimaryRepoPath": "El repo marcado como principal necesita su ruta.",
  "projectform.nameLabel": "Nombre del proyecto",
  "projectform.nameHint": "como quieras llamarlo tú; puedes cambiarlo",
  "projectform.namePlaceholder": "p. ej. TMS",
  "projectform.orgLabel": "Organización de Azure DevOps",
  "projectform.orgPlaceholder": "ProvidenceSolutions",
  "projectform.projectLabel": "Proyecto de Azure DevOps",
  "projectform.projectHint": "donde viven los tickets",
  "projectform.projectPlaceholder": "ProvidenceTMS",
  "projectform.patLabel": "Token de Azure DevOps (PAT)",
  "projectform.patHint": "opcional — sin él se usa la sesión de az login",
  "projectform.patPlaceholderConfigured": "•••••••• (configurado — deja vacío para no cambiarlo)",
  "projectform.patPlaceholderEmpty": "pégalo aquí para configurarlo",
  "projectform.removeTokenLabel": "Quitar el token configurado",
  "projectform.primaryLabel": "principal",
  "projectform.pathExists": "existe",
  "projectform.pathNotExists": "no existe",
  "projectform.removeRepoButton": "quitar",
  "projectform.repoPathPlaceholder": "D:/ruta/al/repo",
  "projectform.repoPathAriaLabel": "Ruta del repo",
  "projectform.pathNotFoundWarning": "No encontré esa carpeta en disco.",
  "projectform.repoLabelPlaceholder": "frontend, backend, app de auth…",
  "projectform.repoLabelAriaLabel": "Descripción del repo",
  "projectform.addRepoButton": "Agregar repo",
  "projectform.editTitle": "Editar proyecto",
}

const EN: Record<string, string> = {
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.dismissError": "Dismiss error",
  "common.projects": "Projects",
  "common.newProject": "New project",
  "common.settings": "Settings",
  "common.discard": "Discard",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.view": "View",
  "common.loading": "loading…",
  "common.languageTitle": "Deliverables language",
  "common.archiveTitle": "Deliverables archive",
  "app.noProjectNamed": "No project named",
  "app.backHome": "Back home",
  "app.loadingTicket": "Loading ticket…",
  "app.unsavedTitle": "You have unsaved changes.",
  "app.unsavedBody": "They will be lost if you leave now.",
  "home.runningPrefix": "running",
  "home.noActiveRuns": "no active runs · the runner runs one at a time",
  "home.tagline": "pick a project to queue tickets · [*] settings for engines, models and archive",
  "home.ticketsSuffix": "tickets",
  "home.openSuffix": "open",
  "home.primaryLabel": "primary:",
  "home.noRepos": "no repos",
  "home.mountedSuffix": "mounted",
  "home.noProjectsYet": "No projects yet. Add one to start queueing tickets.",
  "home.confirmDeleteTitle": "Delete project",
  "home.confirmDeleteBody": "Existing tickets aren't broken: each one saved its own copy of the data. But you won't be able to queue new ones.",
  "topbar.pluginTag": "ticket-agent",
  "topbar.toLightTheme": "Switch to light theme",
  "topbar.toDarkTheme": "Switch to dark theme",
  "info.explanationPrefix": "Explanation",
  "settings.phaseRunTitle": "How each phase runs",
  "settings.globalNextRun": "global · applies to the next run",
  "settings.globalOptional": "global · optional",
  "archive.dirAriaLabel": "Archive directory",
  "archive.dirPlaceholder": "D:/archivo-tickets",
  "archive.savePath": "Save path",
  "language.spanish": "Español",
  "language.english": "English",
  "repotable.noDescription": "no description",
  "repotable.primary": "primary",
  "projectheader.reposSeen": "Repos the agent will see",
  "projectheader.onlyOneRepo": "Just one repo. Add more by editing the project.",
  "ticketlist.originAriaLabel": "Ticket origin",
  "ticketlist.tabAdo": "Azure ticket",
  "ticketlist.tabRequest": "Direct request",
  "ticketlist.workItemIdLabel": "Work item ID",
  "ticketlist.add": "+ Add",
  "ticketlist.workItemUrlHint": "The number at the end of the Azure DevOps URL:",
  "ticketlist.whatDoYouNeedLabel": "What do you need",
  "ticketlist.requestPlaceholder": "What you need, where it lives today (screen, module, repo), why, and how you'll know it's done.",
  "ticketlist.firstLineTitle": "The first line will be the title in the list.",
  "ticketlist.launchPhase1Hint": "Launches Phase 1; the rest launches from the detail view",
  "ticketlist.analyze": "Analyze",
  "ticketlist.reanalyze": "Re-analyze",
  "ticketlist.empty": "No tickets in this project yet. Type an id above to add the first one.",
  "ticketdetail.runHistory": "Run history",
  "ticketdetail.queued": "queued",
  "ticketdetail.noRuns": "No runs yet.",
  "ticketdetail.restore": "Restore",
  "ticketdetail.lastRunLog": "Last run log",
  "ticketdetail.logPlaceholder": "(the log will appear once the run starts)",
  "ticketdetail.confirmDeleteTitle": "Delete ticket",
  "ticketdetail.confirmDeleteBody": "Its runs and logs are deleted. The artifacts the agent wrote in the repo stay where they are.",
  "ticketdetail.fileExistsTitle": "The file already exists",
  "ticketdetail.fileExistsBody": "Replace it with the snapshot's version. The current version is lost (unless another run archived it).",
  "ticketdetail.replace": "Replace",
  "decisions.oneForYou": "decision for you",
  "decisions.manyForYou": "decisions for you",
  "decisions.oneBlocks": "blocks the next phase",
  "decisions.manyBlock": "block the next phase",
  "decisions.allAnswered": "decisions answered",
  "decisions.blocksNextPhase": "Blocks the next phase",
  "decisions.decideWithProposal": "Decide — with a proposal",
  "decisions.answeredSuffix": "answered",
  "decisions.acceptProposal": "Accept proposal",
  "decisions.yourAnswerPlaceholder": "Your answer…",
  "decisions.answerForAriaLabel": "Answer for",
  "decisions.respond": "Respond",
  "status.queued": "queued",
  "status.running": "running",
  "status.analyzed": "analyzed",
  "status.briefed": "briefed",
  "status.surveyed": "surveyed",
  "status.planned": "planned",
  "status.implemented": "implemented",
  "status.error": "error",
  "status.ok": "ok",
  "status.parcial": "partial",
  "status.corriendo": "running",
  "status.pendiente": "pending",
  "status.activeRunSelf": "this run is already in progress",
  "status.activeRunOther": "waiting on #{ado_id} in {project}",
  "status.phaseNotAvailable": "this phase doesn't exist yet",
  "status.deliverableMissing": "{list} declared a deliverable that isn't on disk",
  "status.needsGreen": "needs {list} green",
  "status.orSeparator": "or",
  "phase.analyze": "Analysis",
  "phase.brief": "Brief",
  "phase.survey": "Survey",
  "phase.consolidate": "Consolidation",
  "phase.design": "Plan",
  "phase.implement": "Code",
  "models.infoLabel": "How this works",
  "models.stageAnalyzeTitle": "1 · Understand the ticket",
  "models.stageAnalyzeNote": "Two paths to the same document, and you pick one at launch: Analysis if the project is a single repo; Brief → Survey → Consolidation if there are several.",
  "models.stageDesignTitle": "2 · Plan the change",
  "models.stageImplementTitle": "3 · Write the code",
  "models.tableHeaderPhase": "phase",
  "models.tableHeaderEngine": "engine",
  "models.tableHeaderModel": "model",
  "models.tableHeaderEffort": "effort",
  "models.selectorDefault": "(default)",
  "models.engineLabel": "Engine for",
  "models.modelLabel": "Model for",
  "models.effortLabel": "Effort for",
  "models.saveButton": "Save phase configuration",
  "timeline.preparing": "Preparing…",
  "timeline.prepareRepo": "Prepare repo",
  "timeline.blocksLabel": "blocks",
  "timeline.notAvailableYet": "not available yet",
  "timeline.noRunsShort": "no runs",
  "timeline.oneRun": "run",
  "timeline.manyRuns": "runs",
  "timeline.rerun": "Re-run",
  "timeline.run": "Run",
  "timeline.runWithAdjustmentsTitle": "Run with adjustment instructions",
  "timeline.adjustAndRunAriaLabel": "Adjust and run",
  "timeline.adjust": "Adjust",
  "timeline.taskLabel": "task",
  "timeline.taskOfLabel": "of",
  "timeline.branchLabel": "Branch",
  "timeline.artifactLabel": "Artifact",
  "timeline.filesLabel": "files",
  "timeline.restoreFromArchive": "Restore from archive",
  "timeline.adjustmentFor": "Adjustment for",
  "timeline.howAdjustmentApplies": "How to apply the adjustment",
  "timeline.newSession": "New session",
  "timeline.noPreviousSessionTitle": "This phase has no previous session to continue",
  "timeline.continuePrevious": "Continue the previous one",
  "timeline.continuationLabel": "continuation",
  "timeline.runWithAdjustmentButton": "Run with this adjustment",
  "timeline.viewing": "Viewing",
  "timeline.truncatedNote": "truncated to 512 KB, only the start is shown",
  "timeline.viewRaw": "view raw",
  "timeline.viewRendered": "view rendered",
  "timeline.close": "close",
  "projectform.errorName": "Give the project a name.",
  "projectform.errorOrg": "Missing the Azure DevOps organization.",
  "projectform.errorProject": "Missing the Azure DevOps project.",
  "projectform.errorReposMissing": "You need at least one repo with a path.",
  "projectform.errorPrimaryRepoPath": "The repo marked as primary needs a path.",
  "projectform.nameLabel": "Project name",
  "projectform.nameHint": "call it whatever you like; you can change it",
  "projectform.namePlaceholder": "e.g. TMS",
  "projectform.orgLabel": "Azure DevOps organization",
  "projectform.orgPlaceholder": "ProvidenceSolutions",
  "projectform.projectLabel": "Azure DevOps project",
  "projectform.projectHint": "where the tickets live",
  "projectform.projectPlaceholder": "ProvidenceTMS",
  "projectform.patLabel": "Azure DevOps token (PAT)",
  "projectform.patHint": "optional — without it, the az login session is used",
  "projectform.patPlaceholderConfigured": "•••••••• (configured — leave blank to keep it)",
  "projectform.patPlaceholderEmpty": "paste it here to configure it",
  "projectform.removeTokenLabel": "Remove the configured token",
  "projectform.primaryLabel": "primary",
  "projectform.pathExists": "exists",
  "projectform.pathNotExists": "not found",
  "projectform.removeRepoButton": "remove",
  "projectform.repoPathPlaceholder": "D:/path/to/repo",
  "projectform.repoPathAriaLabel": "Repo path",
  "projectform.pathNotFoundWarning": "Couldn't find that folder on disk.",
  "projectform.repoLabelPlaceholder": "frontend, backend, auth app…",
  "projectform.repoLabelAriaLabel": "Repo description",
  "projectform.addRepoButton": "Add repo",
  "projectform.editTitle": "Edit project",
}

/** A UI string. A missing key is returned as-is instead of breaking the screen:
 *  odd-looking text is a visible bug, a blank screen is a phone call. */
export function t(key: string): string {
  const dict = current === "en" ? EN : ES
  return dict[key] ?? ES[key] ?? key
}

/** Plural for two simple-plural languages. `Intl.PluralRules` is overkill here, and
 *  what came before it — hand-pasting the suffix (`decisión{n > 1 && "es"}`) —
 *  doesn't survive a language where the plural isn't a suffix on the singular. */
export function plural(n: number, one: string, many: string): string {
  return n === 1 ? one : many
}
